import Head from "next/head";
import Image from "next/image";
import {
  Header,
  About,
  Portfolio,
  Skills,
  Service,
  Contact,
  Footer,
} from "../components";
import AppWrapper from "./AppWrapper";
export default function Home() {
  return (
    <AppWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <div className='app__content'>
        <About />
        <Portfolio />
        <Skills />
        <Service />
        <Contact />
      </div>
      <Footer />
    </AppWrapper>
  );
}
