import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  Header,
  About,
  Portfolio,
  Skills,
  Service,
  Contact,
  Footer,
} from "../components";
export default function Home() {
  return (
    <div className={styles.app}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header styles={styles} />
      <div className={styles.app__content}>
        <About styles={styles} />
        <Portfolio styles={styles} />
        <Skills styles={styles} />
        <Service styles={styles} />
        <Contact styles={styles} />
      </div>
      <Footer styles={styles} />
    </div>
  );
}
